/**
 * @sunco/skills-harness - Lint Subsystem Types
 *
 * Types for the lint engine: rule definitions, violation reporting,
 * ESLint boundaries config generation, and lint results.
 *
 * Decisions: D-07 (layer->boundaries mapping), D-08 (structured errors),
 * D-10 (rules in .sun/rules/ as JSON)
 */

// ---------------------------------------------------------------------------
// Lint Rule Definition (D-10)
// ---------------------------------------------------------------------------

/**
 * A lint rule stored in .sun/rules/ as JSON.
 * Rules can be auto-generated by init, promoted from guard patterns,
 * or manually defined by the user.
 */
export interface SunLintRule {
  /** Unique rule identifier (e.g., 'boundary-ui-infra') */
  readonly id: string;
  /** Origin of this rule */
  readonly source: 'init-generated' | 'guard-promoted' | 'user-defined';
  /** ISO 8601 timestamp of rule creation */
  readonly createdAt: string;
  /** Human-readable description of what this rule enforces */
  readonly pattern: string;
  /** ESLint config snippet this rule contributes */
  readonly eslintConfig: {
    settings?: Record<string, unknown>;
    rules?: Record<string, unknown>;
  };
}

// ---------------------------------------------------------------------------
// Lint Violation (D-08)
// ---------------------------------------------------------------------------

/**
 * A structured lint violation with fix instructions.
 * Designed for both human display and agent consumption.
 * "Linter teaches while blocking."
 */
export interface SunLintViolation {
  /** ESLint rule that was violated */
  readonly rule: string;
  /** Absolute file path */
  readonly file: string;
  /** Line number (1-based) */
  readonly line: number;
  /** Column number (1-based) */
  readonly column: number;
  /** Description of the violation */
  readonly violation: string;
  /** Actionable fix instruction */
  readonly fix_instruction: string;
  /** Severity level */
  readonly severity: 'error' | 'warning';
}

// ---------------------------------------------------------------------------
// Lint Result
// ---------------------------------------------------------------------------

/** Aggregated result from a lint run */
export interface LintResult {
  /** All violations found */
  readonly violations: SunLintViolation[];
  /** Number of files that were linted */
  readonly filesLinted: number;
  /** Total error count */
  readonly errorCount: number;
  /** Total warning count */
  readonly warningCount: number;
  /** Whether auto-fix was applied */
  readonly fixApplied: boolean;
}

// ---------------------------------------------------------------------------
// ESLint Boundaries Config (D-07)
// ---------------------------------------------------------------------------

/** An element type definition for eslint-plugin-boundaries */
export interface BoundariesElement {
  /** Element type name matching DetectedLayer.name */
  readonly type: string;
  /** Glob pattern matching this element's files */
  readonly pattern: string;
}

/** A dependency direction rule for eslint-plugin-boundaries */
export interface BoundariesDependencyRule {
  /** Source element types this rule applies to */
  readonly from: Array<{ type: string }>;
  /** Target element types that are allowed to be imported */
  readonly allow: Array<{ type: string }>;
}

/** Complete boundaries configuration generated from detected layers */
export interface BoundariesConfig {
  /** Element type definitions */
  readonly elements: BoundariesElement[];
  /** Dependency direction rules (default policy is 'disallow') */
  readonly dependencyRules: BoundariesDependencyRule[];
}
