/**
 * @sunco/skills-workflow - New Skill (meta-skill)
 *
 * Scaffolds a new SUNCO skill file + colocated test. Superpowers ships
 * a `writing-skills` meta-skill; this is the SUNCO equivalent.
 *
 * By default writes to `packages/skills-extension/src/` (the designated
 * extension point). `--path <dir>` overrides the destination. `--tier
 * user|workflow|admin` and `--kind prompt|deterministic` shape the
 * generated frontmatter.
 *
 * Never overwrites an existing file — callers must pick a unique name.
 * Also never modifies barrel exports or tsup config automatically; the
 * final wiring is a human decision so authors explicitly register their
 * skill.
 */

import { access, mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { defineSkill } from '@sunco/core';
import type { SkillContext, SkillResult } from '@sunco/core';

export type NewSkillKind = 'prompt' | 'deterministic';
export type NewSkillTier = 'user' | 'workflow' | 'admin';

export interface NewSkillOptions {
  name: string;
  kind: NewSkillKind;
  tier: NewSkillTier;
  description: string;
  targetDir: string;
  withTest: boolean;
}

const NAME_PATTERN = /^[a-z][a-z0-9-]*$/;

export function validateSkillName(name: string): string | null {
  if (!name) return 'Skill name is required.';
  if (!NAME_PATTERN.test(name)) {
    return 'Skill name must be lowercase kebab-case (e.g. "my-skill").';
  }
  return null;
}

export function toSkillId(name: string): string {
  return `extension.${name.replace(/-/g, '_')}`;
}

export function toPascal(name: string): string {
  return name
    .split('-')
    .filter(Boolean)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join('');
}

export function buildSkillTemplate(opts: NewSkillOptions): string {
  const id = toSkillId(opts.name);
  const pascal = toPascal(opts.name);
  const permissions =
    opts.kind === 'deterministic'
      ? ''
      : `
  // permissions are declared per ctx.agent.run() call; see shared/tdd-gate.ts
  // or brainstorming.skill.ts for patterns.`;

  return `/**
 * ${pascal} skill — generated by /sunco:new-skill.
 *
 * ${opts.description}
 *
 * Register this skill by:
 *   1. Adding an export to the package barrel (src/index.ts)
 *   2. Adding the entry path to tsup.config.ts
 *   3. Preloading it from packages/cli/src/cli.ts (if it should be a
 *      built-in command rather than a user-space extension)
 */

import { defineSkill } from '@sunco/core';
import type { SkillContext, SkillResult } from '@sunco/core';

export default defineSkill({
  id: '${id}',
  command: '${opts.name}',
  kind: '${opts.kind}',
  stage: 'experimental',
  category: 'workflow',
  routing: 'routable',
  tier: '${opts.tier}',
  description: '${opts.description.replace(/'/g, "\\'")}',
${permissions}
  async execute(ctx: SkillContext): Promise<SkillResult> {
    await ctx.ui.entry({
      title: '${pascal}',
      description: '${opts.description.replace(/'/g, "\\'")}',
    });

    // TODO: implement your skill body here.
    //
    // Common steps:
    //   - Read inputs from ctx.args (positional: ctx.args._)
    //   - Read/write state via ctx.state.get / ctx.state.set
    //   - For prompt skills: call ctx.agent.run({ role, prompt, permissions, timeout })
    //   - Call other skills via ctx.run('<skill.id>', args)
    //
    // Return a SkillResult with { success, summary, data? }.

    await ctx.ui.result({
      success: true,
      title: '${pascal}',
      summary: '${opts.name} scaffolded — replace this body with real logic.',
    });

    return { success: true, summary: '${opts.name} scaffolded.' };
  },
});
`;
}

export function buildTestTemplate(opts: NewSkillOptions): string {
  const id = toSkillId(opts.name);
  return `/**
 * Tests for ${opts.name}.skill.ts (generated by /sunco:new-skill).
 *
 * Replace these placeholders with real assertions that exercise the
 * skill's contract. Prefer testing pure helpers you extract from the
 * skill body over testing the execute() flow directly — it keeps the
 * tests deterministic and fast.
 */

import { describe, it, expect } from 'vitest';
import ${toPascal(opts.name)}Skill from '../${opts.name}.skill.js';

describe('${opts.name} skill', () => {
  it('has the expected skill id', () => {
    expect(${toPascal(opts.name)}Skill.id).toBe('${id}');
  });

  it('is registered as kind=${opts.kind}', () => {
    expect(${toPascal(opts.name)}Skill.kind).toBe('${opts.kind}');
  });
});
`;
}

export interface ScaffoldPlan {
  skillPath: string;
  testPath?: string;
}

export function planScaffold(cwd: string, opts: NewSkillOptions): ScaffoldPlan {
  const baseDir = isAbsolute(opts.targetDir)
    ? opts.targetDir
    : resolve(cwd, opts.targetDir);
  const skillPath = join(baseDir, `${opts.name}.skill.ts`);
  const testPath = opts.withTest
    ? join(baseDir, '__tests__', `${opts.name}.skill.test.ts`)
    : undefined;
  return { skillPath, testPath };
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Deterministic scaffolding — no LLM calls, no network, no git writes.
 * Idempotent: refuses to overwrite files that already exist.
 */
export async function scaffoldSkill(
  cwd: string,
  opts: NewSkillOptions,
): Promise<{ written: string[]; skipped: string[] }> {
  const plan = planScaffold(cwd, opts);
  const written: string[] = [];
  const skipped: string[] = [];

  if (await pathExists(plan.skillPath)) {
    skipped.push(plan.skillPath);
  } else {
    await mkdir(dirname(plan.skillPath), { recursive: true });
    await writeFile(plan.skillPath, buildSkillTemplate(opts), 'utf-8');
    written.push(plan.skillPath);
  }

  if (plan.testPath) {
    if (await pathExists(plan.testPath)) {
      skipped.push(plan.testPath);
    } else {
      await mkdir(dirname(plan.testPath), { recursive: true });
      await writeFile(plan.testPath, buildTestTemplate(opts), 'utf-8');
      written.push(plan.testPath);
    }
  }

  return { written, skipped };
}

export default defineSkill({
  id: 'workflow.new-skill',
  command: 'new-skill',
  kind: 'deterministic',
  stage: 'stable',
  category: 'workflow',
  routing: 'routable',
  tier: 'user',
  description:
    'Scaffold a new SUNCO skill file + colocated test (Superpowers writing-skills parity)',
  options: [
    { flags: '--kind <kind>', description: 'prompt | deterministic (default: prompt)' },
    { flags: '--tier <tier>', description: 'user | workflow | admin (default: user)' },
    { flags: '--description <text>', description: 'One-line description for the frontmatter' },
    { flags: '--path <dir>', description: 'Target directory (default: packages/skills-extension/src)' },
    { flags: '--no-test', description: 'Skip scaffolding the test file' },
  ],

  async execute(ctx: SkillContext): Promise<SkillResult> {
    await ctx.ui.entry({
      title: 'New Skill',
      description: 'Scaffolding a new SUNCO skill (writing-skills parity)',
    });

    const positional = (ctx.args._ as string[] | undefined) ?? [];
    let name = positional[0]?.trim() ?? '';
    if (!name) {
      const answer = await ctx.ui.askText({
        message: 'Skill name (lowercase kebab-case):',
        placeholder: 'e.g. "audit-secrets"',
      });
      name = answer.text.trim();
    }

    const nameErr = validateSkillName(name);
    if (nameErr) {
      await ctx.ui.result({ success: false, title: 'New Skill', summary: nameErr });
      return { success: false, summary: nameErr };
    }

    const kindArg = (ctx.args.kind as string | undefined)?.toLowerCase();
    const kind: NewSkillKind =
      kindArg === 'deterministic' ? 'deterministic' : 'prompt';

    const tierArg = (ctx.args.tier as string | undefined)?.toLowerCase();
    const tier: NewSkillTier =
      tierArg === 'admin' || tierArg === 'workflow' ? tierArg : 'user';

    const description =
      (ctx.args.description as string | undefined) ??
      `${name} skill — generated by /sunco:new-skill`;

    const targetDir =
      (ctx.args.path as string | undefined) ?? 'packages/skills-extension/src';

    const withTest = ctx.args.test !== false && ctx.args['no-test'] !== true;

    try {
      const result = await scaffoldSkill(ctx.cwd, {
        name,
        kind,
        tier,
        description,
        targetDir,
        withTest,
      });

      const summary =
        result.written.length > 0
          ? `Scaffolded ${result.written.length} file(s)`
          : 'No files written (existing files skipped).';

      await ctx.ui.result({
        success: result.written.length > 0,
        title: 'New Skill',
        summary,
        details: [
          ...result.written.map((p) => `wrote: ${p}`),
          ...result.skipped.map((p) => `skipped (exists): ${p}`),
          '',
          'Next steps:',
          `  1. Implement the skill body in ${targetDir}/${name}.skill.ts`,
          `  2. Export it from the package barrel (src/index.ts)`,
          `  3. Add the entry to tsup.config.ts`,
          `  4. (Optional) preload it from packages/cli/src/cli.ts`,
        ],
      });

      return {
        success: result.written.length > 0,
        summary,
        data: { written: result.written, skipped: result.skipped },
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      await ctx.ui.result({ success: false, title: 'New Skill', summary: msg });
      return { success: false, summary: msg };
    }
  },
});
