/**
 * @sunco/skills-workflow - Verify Skill
 *
 * 5-layer Swiss cheese verification pipeline orchestrator.
 * Executes all 5 verification layers sequentially, aggregates findings,
 * computes verdict, handles human gates, and writes VERIFICATION.md.
 *
 * Layers:
 * 1. Multi-Agent Generation (4 experts + coordinator)
 * 2. Deterministic Guardrails (lint + guard)
 * 3. BDD Acceptance Criteria (done criteria + holdout scenarios)
 * 4. Permission Scoping (git diff vs declared scope)
 * 5. Adversarial Verification (adversarial + intent reconstruction)
 *
 * Each layer runs independently -- a layer failure does NOT stop subsequent
 * layers. This is the Swiss cheese model: every layer catches what others miss.
 *
 * Requirements: VRF-01 through VRF-09, REV-02, REV-03
 * Decisions: D-01 (sequential 5-layer), D-02 through D-08, D-21, D-22
 */

import { defineSkill } from '@sunco/core';
import type { SkillContext, SkillResult } from '@sunco/core';
import { writeFile, mkdir, readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { simpleGit } from 'simple-git';
import { resolvePhaseDir } from './shared/phase-reader.js';
import { parsePlanMd } from './shared/plan-parser.js';
import type { ParsedPlan } from './shared/plan-parser.js';
import type { VerifyFinding, VerifyReport, VerifyVerdict, LayerResult } from './shared/verify-types.js';
import {
  runLayer1MultiAgent,
  runLayer2Deterministic,
  runLayer3Acceptance,
  runLayer4PermissionScope,
  runLayer5Adversarial,
} from './shared/verify-layers.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Layer names for error capture */
const LAYER_NAMES = [
  'Multi-Agent Generation',
  'Deterministic Guardrails',
  'BDD Acceptance Criteria',
  'Permission Scoping',
  'Adversarial Verification',
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Compute verdict from findings.
 * FAIL: any critical or high severity.
 * WARN: any medium or low severity.
 * PASS: no findings.
 */
function computeVerdict(findings: VerifyFinding[]): VerifyVerdict {
  if (findings.some((f) => f.severity === 'critical' || f.severity === 'high')) {
    return 'FAIL';
  }
  if (findings.length > 0) {
    return 'WARN';
  }
  return 'PASS';
}

/**
 * Format the VERIFICATION.md report content.
 */
function formatVerificationMd(report: VerifyReport): string {
  const lines: string[] = [];

  lines.push('# Verification Report');
  lines.push('');
  lines.push(`**Verdict:** ${report.verdict}`);
  lines.push(`**Timestamp:** ${report.timestamp}`);
  lines.push(`**Total findings:** ${report.findings.length}`);
  lines.push(`**Human gate required:** ${report.humanGateRequired ? 'Yes' : 'No'}`);
  lines.push('');

  for (const layer of report.layers) {
    lines.push(`## Layer ${layer.layer}: ${layer.name}`);
    lines.push('');
    lines.push(`**Status:** ${layer.passed ? 'PASS' : 'FAIL'}`);
    lines.push(`**Duration:** ${layer.durationMs}ms`);
    lines.push(`**Findings:** ${layer.findings.length}`);
    lines.push('');

    if (layer.findings.length > 0) {
      for (const finding of layer.findings) {
        const humanTag = finding.humanRequired ? ' [HUMAN REQUIRED]' : '';
        lines.push(`- **[${finding.severity.toUpperCase()}]** (${finding.source})${humanTag}: ${finding.description}`);
        if (finding.file) {
          lines.push(`  - File: ${finding.file}${finding.line ? `:${finding.line}` : ''}`);
        }
        if (finding.suggestion) {
          lines.push(`  - Suggestion: ${finding.suggestion}`);
        }
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by sunco verify at ${report.timestamp}*`);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Skill Definition
// ---------------------------------------------------------------------------

export default defineSkill({
  id: 'workflow.verify',
  command: 'verify',
  kind: 'prompt',
  stage: 'stable',
  category: 'workflow',
  routing: 'directExec',
  description: 'Run 5-layer Swiss cheese verification pipeline',

  options: [
    { flags: '-p, --phase <number>', description: 'Which phase to verify' },
    { flags: '--auto', description: 'Skip human gate prompts (for CI)' },
    { flags: '--strict', description: 'Fail on humanRequired findings' },
  ],

  async execute(ctx: SkillContext): Promise<SkillResult> {
    // --- Entry ---
    await ctx.ui.entry({
      title: 'Verify',
      description: 'Starting 5-layer Swiss cheese verification...',
    });

    // --- Step 1: Resolve phase ---
    const phaseArg = ctx.args.phase as number | undefined;
    if (phaseArg === undefined) {
      const msg = 'Usage: sunco verify --phase <number>';
      await ctx.ui.result({ success: false, title: 'Verify', summary: msg });
      return { success: false, summary: msg };
    }

    const phaseDir = await resolvePhaseDir(ctx.cwd, phaseArg);
    if (!phaseDir) {
      const msg = `Phase ${phaseArg} directory not found`;
      await ctx.ui.result({ success: false, title: 'Verify', summary: msg });
      return { success: false, summary: msg };
    }

    // --- Step 2: Read PLAN.md files ---
    let entries: string[];
    try {
      entries = await readdir(phaseDir);
    } catch {
      const msg = `Cannot read phase directory: ${phaseDir}`;
      await ctx.ui.result({ success: false, title: 'Verify', summary: msg });
      return { success: false, summary: msg };
    }

    const planFiles = entries.filter(
      (e: string) => e.match(/-PLAN\.md$/) && !e.includes('SUMMARY'),
    );

    const plans: ParsedPlan[] = [];
    for (const file of planFiles) {
      try {
        const content = await readFile(join(phaseDir, file), 'utf-8');
        plans.push(parsePlanMd(content));
      } catch (err) {
        ctx.log.warn(`Failed to parse plan ${file}`, { error: err });
      }
    }

    // --- Step 3: Get git diff ---
    let diff = '';
    try {
      const git = simpleGit(ctx.cwd);
      const log = await git.log({ maxCount: 50 });
      const padded = String(phaseArg).padStart(2, '0');

      const phaseCommits = log.all.filter(
        (c) => c.message.includes(`(${padded}-`) || c.message.includes(`Phase ${phaseArg}`),
      );

      if (phaseCommits.length > 0) {
        const oldestCommit = phaseCommits[phaseCommits.length - 1]!;
        diff = await git.diff([`${oldestCommit.hash}^..HEAD`]);
      } else {
        const staged = await git.diff(['--cached']);
        const unstaged = await git.diff();
        diff = [staged, unstaged].filter(Boolean).join('\n');
      }
    } catch {
      ctx.log.warn('Git diff failed -- using empty diff');
    }

    // --- Step 4: Execute all 5 layers sequentially (D-01) ---
    const layerProgress = ctx.ui.progress({
      title: 'Verification layers',
      total: 5,
    });

    const layerFunctions = [
      () => runLayer1MultiAgent(ctx, diff, phaseDir),
      () => runLayer2Deterministic(ctx),
      () => runLayer3Acceptance(ctx, plans, phaseDir),
      () => runLayer4PermissionScope(ctx, plans),
      () => runLayer5Adversarial(ctx, diff, phaseDir),
    ];

    const layerResults: LayerResult[] = [];

    for (let i = 0; i < layerFunctions.length; i++) {
      const fn = layerFunctions[i]!;
      const layerName = LAYER_NAMES[i]!;

      layerProgress.update({
        completed: i,
        message: `Layer ${i + 1}: ${layerName}`,
      });

      try {
        const result = await fn();
        layerResults.push(result);
      } catch (err) {
        // Layer failure does NOT stop subsequent layers (Swiss cheese model)
        ctx.log.warn(`Layer ${i + 1} (${layerName}) threw`, { error: err });
        layerResults.push({
          layer: i + 1,
          name: layerName,
          findings: [
            {
              layer: i + 1,
              source: 'correctness' as VerifyFinding['source'],
              severity: 'low',
              description: `Layer ${i + 1} error: ${err instanceof Error ? err.message : String(err)}`,
            },
          ],
          passed: true,
          durationMs: 0,
        });
      }
    }

    layerProgress.update({ completed: 5, message: 'All layers complete' });
    layerProgress.done({ summary: 'All 5 layers executed' });

    // --- Step 5: Aggregate findings ---
    const allFindings: VerifyFinding[] = [];
    for (const layer of layerResults) {
      allFindings.push(...layer.findings);
    }

    // --- Step 6: Compute verdict ---
    let verdict = computeVerdict(allFindings);

    // --- Step 7: Human gate ---
    const humanGateRequired = allFindings.some((f) => f.humanRequired === true);
    const isAuto = ctx.args.auto === true;
    const isStrict = ctx.args.strict === true;

    // --strict: humanRequired findings = FAIL
    if (isStrict && humanGateRequired) {
      verdict = 'FAIL';
    }

    // Human gate prompt (unless --auto)
    if (humanGateRequired && !isAuto && !isStrict) {
      const humanFindings = allFindings.filter((f) => f.humanRequired);
      const humanSummary = humanFindings
        .map((f) => `- [${f.severity}] ${f.source}: ${f.description}`)
        .join('\n');

      const gateChoice = await ctx.ui.ask({
        message: `${humanFindings.length} finding(s) require human review:\n${humanSummary}\n\nApprove?`,
        options: [
          { id: 'approve', label: 'Approve' },
          { id: 'reject', label: 'Reject — override verdict to FAIL' },
        ],
      });

      if (gateChoice.selectedId === 'reject') {
        verdict = 'FAIL';
        ctx.log.warn('Human gate rejected — verdict overridden to FAIL');
      }
    }

    // --- Step 8: Build report ---
    const report: VerifyReport = {
      verdict,
      layers: layerResults,
      findings: allFindings,
      humanGateRequired,
      timestamp: new Date().toISOString(),
    };

    // --- Step 9: Write VERIFICATION.md ---
    const verificationContent = formatVerificationMd(report);
    const verificationPath = join(phaseDir, 'VERIFICATION.md');
    await mkdir(phaseDir, { recursive: true });
    await writeFile(verificationPath, verificationContent, 'utf-8');
    ctx.log.info('VERIFICATION.md written', { path: verificationPath });

    // --- Step 10: Store result in state ---
    await ctx.state.set('verify.lastResult', {
      verdict: report.verdict,
      findingCount: allFindings.length,
      timestamp: report.timestamp,
    });

    // --- Step 11: Return result ---
    const success = verdict !== 'FAIL';
    const summary = `Verification ${verdict}: ${allFindings.length} finding(s) across 5 layers`;

    await ctx.ui.result({
      success,
      title: 'Verify',
      summary,
      details: [
        `Verdict: ${verdict}`,
        `Findings: ${allFindings.length}`,
        `Human gate: ${humanGateRequired ? 'required' : 'not required'}`,
        `Output: ${verificationPath}`,
      ],
    });

    return {
      success,
      summary,
      data: report,
    };
  },
});
