/**
 * @sunco/skills-harness - Workspace Initializer
 *
 * Creates the .sun/ workspace directory structure, generates config.toml
 * from detection results, and produces lint rule JSON files.
 *
 * Decisions: D-04 (.sun/ init), D-05 (presets), D-10 (lint rule generation)
 */

import { stringify } from 'smol-toml';
import { writeFile, mkdir, access } from 'node:fs/promises';
import { join } from 'node:path';
import type { FileStoreApi } from '@sunco/core';
import type { InitResult, DetectedLayer } from './types.js';
import { resolvePreset, type ProjectPreset } from './presets.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface InitializeWorkspaceOpts {
  /** Complete detection result from all three detectors */
  initResult: InitResult;
  /** FileStoreApi for writing to .sun/ */
  fileStore: FileStoreApi;
  /** Project root directory (cwd) for writing CLAUDE.md and .claude/rules/ */
  cwd: string;
  /** Overwrite existing .sun/ configuration (default: false) */
  force?: boolean;
}

export interface InitializeWorkspaceResult {
  /** Path to the generated config file (relative to .sun/) */
  configPath: string;
  /** Number of lint rule files generated */
  rulesGenerated: number;
  /** Resolved project preset */
  preset: ProjectPreset;
  /** Whether CLAUDE.md was generated (false if already existed) */
  claudeMdGenerated: boolean;
  /** Number of .claude/rules/ files generated */
  claudeRulesGenerated: number;
}

// ---------------------------------------------------------------------------
// Config Generation
// ---------------------------------------------------------------------------

/**
 * Build the TOML config object from detection results and preset.
 */
function buildConfigToml(initResult: InitResult, preset: ProjectPreset): string {
  const { ecosystems, layers, conventions } = initResult;

  // Build the TOML data structure
  const config: Record<string, unknown> = {
    stack: {
      ecosystems: ecosystems.ecosystems,
      primary: ecosystems.primaryEcosystem ?? 'unknown',
      preset: preset.id,
    },
    layers: {
      source_root: layers.sourceRoot ?? '',
      detected: layers.layers.map((layer) => ({
        name: layer.name,
        pattern: layer.pattern,
      })),
    },
    conventions: {
      naming: conventions.naming,
      import_style: conventions.importStyle,
      export_style: conventions.exportStyle,
      test_organization: conventions.testOrganization,
    },
  };

  return `# Auto-generated by sunco init\n${stringify(config)}\n`;
}

// ---------------------------------------------------------------------------
// Lint Rule Generation (D-10)
// ---------------------------------------------------------------------------

/**
 * Generate the arch-layers.json boundary lint rule from detected layers.
 *
 * Creates an ESLint config fragment compatible with eslint-plugin-boundaries.
 * Each detected layer becomes a boundary element, and dependency direction
 * rules are derived from canImportFrom.
 */
function generateArchLayersRule(layers: DetectedLayer[]): string {
  // Build boundary elements from detected layers
  const elements = layers.map((layer) => ({
    type: layer.name,
    pattern: layer.pattern,
  }));

  // Build dependency rules from canImportFrom
  const dependencyRules = layers
    .filter((layer) => layer.canImportFrom.length > 0)
    .map((layer) => ({
      from: [{ type: layer.name }],
      allow: layer.canImportFrom.map((name) => ({ type: name })),
    }));

  const rule = {
    id: 'arch-layers',
    source: 'init-generated',
    createdAt: new Date().toISOString(),
    pattern: 'Architecture layer dependency boundaries',
    eslintConfig: {
      settings: {
        'boundaries/elements': elements,
      },
      rules: {
        'boundaries/dependencies': [
          2,
          {
            default: 'disallow',
            rules: dependencyRules,
          },
        ],
      },
    },
  };

  return JSON.stringify(rule, null, 2);
}

// ---------------------------------------------------------------------------
// Main Export
// ---------------------------------------------------------------------------

/**
 * Initialize the .sun/ workspace with config, rules, and directory structure.
 *
 * Steps:
 * 1. Check if config.toml exists (skip if not force)
 * 2. Resolve project preset from detected ecosystems
 * 3. Generate and write config.toml
 * 4. Generate and write arch-layers.json lint rule
 * 5. Create placeholder .gitkeep files for tribal/, scenarios/, planning/
 *
 * @param opts - Options with initResult, fileStore, and optional force flag
 * @returns Result with configPath, rulesGenerated count, and resolved preset
 */
export async function initializeWorkspace(
  opts: InitializeWorkspaceOpts,
): Promise<InitializeWorkspaceResult> {
  const { initResult, fileStore, force = false } = opts;

  // Resolve preset from detected ecosystems (D-05)
  const preset = resolvePreset(initResult.ecosystems.ecosystems);

  // Check if config already exists
  const existing = await fileStore.exists('', 'config.toml');
  if (existing && !force) {
    return {
      configPath: 'config.toml',
      rulesGenerated: 0,
      preset,
      claudeMdGenerated: false,
      claudeRulesGenerated: 0,
    };
  }

  // Generate and write config.toml
  const configContent = buildConfigToml(initResult, preset);
  await fileStore.write('', 'config.toml', configContent);

  // Generate and write lint rules (D-10)
  let rulesGenerated = 0;
  if (initResult.layers.layers.length > 0) {
    const ruleContent = generateArchLayersRule(initResult.layers.layers);
    await fileStore.write('rules', 'arch-layers.json', ruleContent);
    rulesGenerated++;
  }

  // Create placeholder directories (D-04)
  await fileStore.write('tribal', '.gitkeep', '');
  await fileStore.write('scenarios', '.gitkeep', '');
  await fileStore.write('planning', '.gitkeep', '');

  // Generate thin CLAUDE.md + .claude/rules/ (Memory Strategy dogfood)
  const { claudeMdGenerated, claudeRulesGenerated } = await generateClaudeMemoryFiles(
    opts.cwd, initResult, preset, force,
  );

  return {
    configPath: 'config.toml',
    rulesGenerated,
    preset,
    claudeMdGenerated,
    claudeRulesGenerated,
  };
}

// ---------------------------------------------------------------------------
// CLAUDE.md + .claude/rules/ generation (Memory Strategy)
// ---------------------------------------------------------------------------

async function fileExists(filePath: string): Promise<boolean> {
  try { await access(filePath); return true; } catch { return false; }
}

async function generateClaudeMemoryFiles(
  cwd: string,
  initResult: InitResult,
  preset: ProjectPreset,
  force: boolean,
): Promise<{ claudeMdGenerated: boolean; claudeRulesGenerated: number }> {
  const claudeMdPath = join(cwd, 'CLAUDE.md');
  const rulesDir = join(cwd, '.claude', 'rules');
  let claudeMdGenerated = false;
  let claudeRulesGenerated = 0;

  // Generate thin root CLAUDE.md (≤60 lines)
  if (force || !(await fileExists(claudeMdPath))) {
    const ecosystems = initResult.ecosystems.ecosystems.join(', ') || 'unknown';
    const primaryEco = initResult.ecosystems.primaryEcosystem ?? 'unknown';

    const thinRoot = [
      `## Project`,
      ``,
      `${primaryEco} project. Stack: ${ecosystems}. Preset: ${preset.id}.`,
      ``,
      `## Constraints`,
      ``,
      `- Follow conventions in .claude/rules/`,
      `- Run \`sunco lint\` before committing`,
      `- Run \`sunco verify\` before shipping`,
      ``,
      `## Key Rules`,
      ``,
      `- ESM-only imports (.js extension even for .ts files)`,
      `- Prefer editing existing files over creating new ones`,
      `- No hardcoded paths — use config/env resolution`,
      `- Tests required for new functionality`,
      ``,
      `## Architecture`,
      ``,
      `See .claude/rules/architecture.md for structure details.`,
      `See .claude/rules/conventions.md for naming and import patterns.`,
      ``,
      `## Workflow`,
      ``,
      `Use /sunco:* commands for the development lifecycle:`,
      `- /sunco:discuss → /sunco:plan → /sunco:execute → /sunco:verify → /sunco:ship`,
      ``,
    ].join('\n');

    await writeFile(claudeMdPath, thinRoot, 'utf8');
    claudeMdGenerated = true;
  }

  // Generate .claude/rules/ directory with preset-appropriate rules
  await mkdir(rulesDir, { recursive: true });

  // Architecture rule (always generated)
  const archRulePath = join(rulesDir, 'architecture.md');
  if (force || !(await fileExists(archRulePath))) {
    const layers = initResult.layers.layers.map((l) => `- **${l.name}**: \`${l.pattern}\``).join('\n');
    await writeFile(archRulePath, [
      `---`,
      `description: Architecture layers and dependency boundaries`,
      `globs:`,
      `  - "src/**"`,
      `  - "packages/**"`,
      `---`,
      ``,
      `## Detected Layers`,
      ``,
      layers || '- No layers detected. Run `sunco init` after structuring your source.',
      ``,
      `## Dependency Rules`,
      ``,
      `- Higher layers may import from lower layers`,
      `- Lower layers must NOT import from higher layers`,
      `- Use \`sunco lint\` to enforce boundaries`,
      ``,
    ].join('\n'), 'utf8');
    claudeRulesGenerated++;
  }

  // Conventions rule
  const convRulePath = join(rulesDir, 'conventions.md');
  if (force || !(await fileExists(convRulePath))) {
    const naming = initResult.conventions.naming;
    const importStyle = initResult.conventions.importStyle;
    await writeFile(convRulePath, [
      `---`,
      `description: File naming, import style, and testing conventions`,
      `globs:`,
      `  - "**/*.ts"`,
      `  - "**/*.tsx"`,
      `  - "**/*.js"`,
      `---`,
      ``,
      `## Naming: ${naming}`,
      `## Import Style: ${importStyle}`,
      `## Export Style: ${initResult.conventions.exportStyle}`,
      `## Test Organization: ${initResult.conventions.testOrganization}`,
      ``,
    ].join('\n'), 'utf8');
    claudeRulesGenerated++;
  }

  return { claudeMdGenerated, claudeRulesGenerated };
}
