import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/status.skill.ts',
    'src/next.skill.ts',
    'src/context.skill.ts',
    'src/pause.skill.ts',
    'src/resume.skill.ts',
    'src/note.skill.ts',
    'src/todo.skill.ts',
    'src/seed.skill.ts',
    'src/backlog.skill.ts',
    'src/phase.skill.ts',
    'src/settings.skill.ts',
    'src/brainstorming.skill.ts',
    'src/new.skill.ts',
    'src/new-skill.skill.ts',
    'src/orchestrate.skill.ts',
    'src/scan.skill.ts',
    'src/discuss.skill.ts',
    'src/assume.skill.ts',
    'src/research.skill.ts',
    'src/plan.skill.ts',
    'src/ultraplan.skill.ts',
    'src/execute.skill.ts',
    'src/review.skill.ts',
    'src/ceo-review.skill.ts',
    'src/eng-review.skill.ts',
    'src/design-review.skill.ts',
    'src/compound.skill.ts',
    'src/verify.skill.ts',
    'src/validate.skill.ts',
    'src/test-gen.skill.ts',
    'src/ship.skill.ts',
    'src/release.skill.ts',
    'src/milestone.skill.ts',
    'src/auto.skill.ts',
    'src/quick.skill.ts',
    'src/fast.skill.ts',
    'src/do.skill.ts',
    'src/debug.skill.ts',
    // Phase 33 Wave 3: diagnose.skill.ts removed — absorbed into debug --parse
    // Phase 33 Wave 3: forensics.skill.ts removed — absorbed into debug --postmortem
    'src/query.skill.ts',
    'src/export.skill.ts',
    'src/graph.skill.ts',
    'src/doc.skill.ts',
    'src/dashboard-tui.tsx',
  ],
  format: ['esm'],
  target: 'node22',
  dts: true,
  clean: true,
  external: [
    '@sunco/core',
    'simple-git',
    'ink',
    'react',
  ],
  esbuildOptions(options) {
    options.jsx = 'automatic';
  },
});
