import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/status.skill.ts',
    'src/next.skill.ts',
    'src/context.skill.ts',
    'src/pause.skill.ts',
    'src/resume.skill.ts',
    'src/note.skill.ts',
    'src/todo.skill.ts',
    'src/seed.skill.ts',
    'src/backlog.skill.ts',
    'src/phase.skill.ts',
    'src/settings.skill.ts',
    'src/new.skill.ts',
    'src/scan.skill.ts',
    'src/discuss.skill.ts',
    'src/assume.skill.ts',
    'src/research.skill.ts',
    'src/plan.skill.ts',
    'src/execute.skill.ts',
    'src/review.skill.ts',
    'src/verify.skill.ts',
    'src/validate.skill.ts',
    'src/test-gen.skill.ts',
    'src/ship.skill.ts',
    'src/release.skill.ts',
    'src/milestone.skill.ts',
    'src/auto.skill.ts',
    'src/quick.skill.ts',
    'src/fast.skill.ts',
    'src/do.skill.ts',
    'src/debug.skill.ts',
    'src/diagnose.skill.ts',
    'src/forensics.skill.ts',
    'src/query.skill.ts',
    'src/export.skill.ts',
    'src/graph.skill.ts',
    'src/doc.skill.ts',
  ],
  format: ['esm'],
  target: 'node22',
  dts: true,
  clean: true,
  external: [
    '@sunco/core',
    'simple-git',
  ],
});
