/**
 * Tests for discuss.skill.ts
 *
 * Verifies:
 * - Skill metadata (id, command, kind, stage, category, routing)
 * - No-provider fallback (graceful error)
 * - Missing ROADMAP.md error
 * - Normal flow: analyze -> ask -> deep-dive -> scenarios -> write CONTEXT.md
 * - Agent parse failure fallback (non-JSON gray areas)
 * - Partial failure: scenario generation fails, CONTEXT.md still written
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Mocks (must be before imports)
// ---------------------------------------------------------------------------

vi.mock('node:fs/promises', () => ({
  readFile: vi.fn(),
}));

vi.mock('../shared/phase-reader.js', () => ({
  resolvePhaseDir: vi.fn(),
  readPhaseArtifact: vi.fn(),
  writePhaseArtifact: vi.fn(),
}));

vi.mock('../shared/roadmap-parser.js', () => ({
  parseRoadmap: vi.fn(),
}));

vi.mock('../shared/state-reader.js', () => ({
  parseStateMd: vi.fn(),
}));

import { readFile } from 'node:fs/promises';
import { resolvePhaseDir, writePhaseArtifact } from '../shared/phase-reader.js';
import { parseRoadmap } from '../shared/roadmap-parser.js';
import { parseStateMd } from '../shared/state-reader.js';
import discussSkill from '../discuss.skill.js';
import type { SkillContext } from '@sunco/core';
import type { AgentResult } from '@sunco/core';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const MOCK_GRAY_AREAS_OUTPUT = `\`\`\`json
{
  "id": "ga-01",
  "question": "How should context sections be validated?",
  "options": [
    { "id": "opt-a", "label": "Zod schema", "description": "Validate with Zod", "recommended": true },
    { "id": "opt-b", "label": "Regex", "description": "Validate with regex", "recommended": false }
  ],
  "defaultId": "opt-a"
}
\`\`\`
---GRAY_AREA---
\`\`\`json
{
  "id": "ga-02",
  "question": "Where should scenarios be stored?",
  "options": [
    { "id": "opt-a", "label": ".sun/scenarios", "description": "In .sun dir", "recommended": true },
    { "id": "opt-b", "label": ".planning", "description": "In .planning dir", "recommended": false }
  ],
  "defaultId": "opt-a"
}
\`\`\``;

const MOCK_DEEPDIVE_OUTPUT = `DECISION: Use Zod schema validation for context sections with strict type checking
FOLLOW_UP: none
CONFLICTS: none`;

const MOCK_SCENARIO_OUTPUT = `# Scenario: Validates context sections have required fields

## Given
A CONTEXT.md file is generated by the discuss skill

## When
The verification agent checks the file structure

## Then
All 6 required sections (<domain>, <decisions>, <canonical_refs>, <code_context>, <specifics>, <deferred>) are present
---SCENARIO---
# Scenario: Scenarios stored in correct location

## Given
The discuss skill completes successfully

## When
BDD holdout scenarios are written

## Then
Files are created in .sun/scenarios/ with naming pattern scenario-{phase}-{idx}.md`;

const MOCK_ROADMAP_CONTENT = '# Roadmap\n...';

const MOCK_STATE_CONTENT = `---
status: executing
progress:
  total_phases: 10
  completed_phases: 4
---

# Project State

## Current Position

Phase: 05 (context-planning) -- EXECUTING
Plan: 1 of 5
`;

function createMockAgentResult(
  overrides: Partial<AgentResult> = {},
): AgentResult {
  return {
    providerId: 'claude-code-cli',
    success: true,
    outputText: '# Test output',
    artifacts: [],
    warnings: [],
    usage: { estimated: true, wallTimeMs: 1000 },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Mock context factory
// ---------------------------------------------------------------------------

function createMockContext(
  overrides: Partial<SkillContext> = {},
): SkillContext {
  return {
    config: {} as SkillContext['config'],
    state: {
      get: vi.fn().mockResolvedValue(null),
      set: vi.fn().mockResolvedValue(undefined),
      delete: vi.fn().mockResolvedValue(false),
      list: vi.fn().mockResolvedValue([]),
      has: vi.fn().mockResolvedValue(false),
    } as unknown as SkillContext['state'],
    fileStore: {
      read: vi.fn().mockResolvedValue(undefined),
      write: vi.fn().mockResolvedValue(undefined),
      list: vi.fn().mockResolvedValue([]),
      remove: vi.fn().mockResolvedValue(false),
      exists: vi.fn().mockResolvedValue(false),
    } as unknown as SkillContext['fileStore'],
    agent: {
      run: vi.fn().mockResolvedValue(createMockAgentResult()),
      crossVerify: vi.fn().mockResolvedValue([]),
      listProviders: vi.fn().mockResolvedValue(['claude-code-cli']),
    } as unknown as SkillContext['agent'],
    recommend: {
      getRecommendations: vi.fn().mockReturnValue([]),
      getTopRecommendation: vi.fn().mockReturnValue(undefined),
    },
    ui: {
      entry: vi.fn().mockResolvedValue(undefined),
      ask: vi.fn().mockResolvedValue({
        selectedId: 'opt-a',
        selectedLabel: 'Zod schema',
        source: 'default',
      }),
      askText: vi.fn().mockResolvedValue({ text: '', source: 'default' }),
      progress: vi.fn().mockReturnValue({
        update: vi.fn(),
        done: vi.fn(),
      }),
      result: vi.fn().mockResolvedValue(undefined),
    },
    log: {
      debug: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
    },
    run: vi.fn().mockResolvedValue({ success: true }),
    cwd: '/test/project',
    args: {},
    signal: new AbortController().signal,
    ...overrides,
  } as unknown as SkillContext;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('discussSkill', () => {
  const mockedReadFile = vi.mocked(readFile);
  const mockedResolvePhaseDir = vi.mocked(resolvePhaseDir);
  const mockedWritePhaseArtifact = vi.mocked(writePhaseArtifact);
  const mockedParseRoadmap = vi.mocked(parseRoadmap);
  const mockedParseStateMd = vi.mocked(parseStateMd);

  beforeEach(() => {
    vi.clearAllMocks();

    // Default mocks for normal flow
    mockedReadFile.mockImplementation((path: any) => {
      const pathStr = String(path);
      if (pathStr.includes('STATE.md')) {
        return Promise.resolve(MOCK_STATE_CONTENT);
      }
      if (pathStr.includes('ROADMAP.md')) {
        return Promise.resolve(MOCK_ROADMAP_CONTENT);
      }
      return Promise.reject(new Error(`Unexpected readFile: ${pathStr}`));
    });

    mockedResolvePhaseDir.mockResolvedValue('/test/project/.planning/phases/05-context-planning');
    mockedWritePhaseArtifact.mockResolvedValue('/test/project/.planning/phases/05-context-planning/05-CONTEXT.md');

    mockedParseStateMd.mockReturnValue({
      phase: 5,
      plan: '1 of 5',
      status: 'executing',
      lastActivity: '2026-03-28',
      progress: {
        totalPhases: 10,
        completedPhases: 4,
        totalPlans: 35,
        completedPlans: 30,
        percent: 0,
      },
    });

    mockedParseRoadmap.mockReturnValue({
      phases: [
        {
          number: 5,
          name: 'Context Planning',
          description: 'Extract design decisions through agent-guided conversation',
          completed: false,
          requirements: ['WF-09', 'WF-10'],
          plans: [],
          planCount: 5,
          completedCount: 0,
        },
      ],
      progress: [],
    });
  });

  // -------------------------------------------------------------------------
  // Metadata
  // -------------------------------------------------------------------------

  it('has correct skill metadata', () => {
    expect(discussSkill.id).toBe('workflow.discuss');
    expect(discussSkill.command).toBe('discuss');
    expect(discussSkill.kind).toBe('prompt');
    expect(discussSkill.stage).toBe('stable');
    expect(discussSkill.category).toBe('workflow');
    expect(discussSkill.routing).toBe('routable');
  });

  // -------------------------------------------------------------------------
  // No provider
  // -------------------------------------------------------------------------

  it('returns failure when no AI provider is available', async () => {
    const ctx = createMockContext({
      agent: {
        run: vi.fn(),
        crossVerify: vi.fn(),
        listProviders: vi.fn().mockResolvedValue([]),
      } as unknown as SkillContext['agent'],
    });

    const result = await discussSkill.execute(ctx);

    expect(result.success).toBe(false);
    expect(result.summary).toMatch(/no ai provider/i);
  });

  // -------------------------------------------------------------------------
  // Missing ROADMAP
  // -------------------------------------------------------------------------

  it('returns failure when ROADMAP.md is not found', async () => {
    mockedReadFile.mockImplementation((path: any) => {
      const pathStr = String(path);
      if (pathStr.includes('STATE.md')) {
        return Promise.resolve(MOCK_STATE_CONTENT);
      }
      return Promise.reject(new Error('ENOENT'));
    });

    const ctx = createMockContext();
    const result = await discussSkill.execute(ctx);

    expect(result.success).toBe(false);
    expect(result.summary).toMatch(/roadmap/i);
  });

  // -------------------------------------------------------------------------
  // Normal flow
  // -------------------------------------------------------------------------

  it('executes full flow: analyze -> ask -> deep-dive -> scenarios -> write CONTEXT.md', async () => {
    let agentCallCount = 0;
    const ctx = createMockContext({
      agent: {
        run: vi.fn().mockImplementation(() => {
          agentCallCount++;
          if (agentCallCount === 1) {
            // Analyze: return gray areas
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_GRAY_AREAS_OUTPUT }));
          }
          if (agentCallCount <= 3) {
            // Deep-dive: return decision for each gray area
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_DEEPDIVE_OUTPUT }));
          }
          // Scenario generation
          return Promise.resolve(createMockAgentResult({ outputText: MOCK_SCENARIO_OUTPUT }));
        }),
        crossVerify: vi.fn().mockResolvedValue([]),
        listProviders: vi.fn().mockResolvedValue(['claude-code-cli']),
      } as unknown as SkillContext['agent'],
    });

    const result = await discussSkill.execute(ctx);

    expect(result.success).toBe(true);

    // Should have asked user about gray areas (2 gray areas)
    expect(ctx.ui.ask).toHaveBeenCalledTimes(2);

    // Should have written CONTEXT.md
    expect(mockedWritePhaseArtifact).toHaveBeenCalled();
    const writeCall = mockedWritePhaseArtifact.mock.calls[0];
    expect(writeCall[0]).toBe('/test/project');
    expect(writeCall[1]).toBe(5);
    expect(String(writeCall[3])).toContain('CONTEXT.md');

    // CONTEXT.md content should contain required sections
    const contextContent = String(writeCall[4]);
    expect(contextContent).toContain('<domain>');
    expect(contextContent).toContain('<decisions>');
    expect(contextContent).toContain('<canonical_refs>');
    expect(contextContent).toContain('<code_context>');
    expect(contextContent).toContain('<specifics>');
    expect(contextContent).toContain('<deferred>');

    // Should have written scenarios
    expect(ctx.fileStore.write).toHaveBeenCalled();
  });

  // -------------------------------------------------------------------------
  // Agent parse failure fallback
  // -------------------------------------------------------------------------

  it('falls back to text question when agent output cannot be parsed as gray areas', async () => {
    let agentCallCount = 0;
    const ctx = createMockContext({
      agent: {
        run: vi.fn().mockImplementation(() => {
          agentCallCount++;
          if (agentCallCount === 1) {
            // Return non-parseable output
            return Promise.resolve(createMockAgentResult({
              outputText: 'Here are some thoughts about gray areas without proper JSON format...',
            }));
          }
          if (agentCallCount === 2) {
            // Deep-dive for single text area
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_DEEPDIVE_OUTPUT }));
          }
          // Scenario generation
          return Promise.resolve(createMockAgentResult({ outputText: MOCK_SCENARIO_OUTPUT }));
        }),
        crossVerify: vi.fn().mockResolvedValue([]),
        listProviders: vi.fn().mockResolvedValue(['claude-code-cli']),
      } as unknown as SkillContext['agent'],
    });

    const result = await discussSkill.execute(ctx);

    // Should still succeed -- fallback to askText
    expect(result.success).toBe(true);
    // Should have used askText fallback (not ask with options)
    expect(ctx.ui.askText).toHaveBeenCalled();
  });

  // -------------------------------------------------------------------------
  // Scenario generation failure
  // -------------------------------------------------------------------------

  it('still writes CONTEXT.md when scenario generation fails', async () => {
    let agentCallCount = 0;
    const ctx = createMockContext({
      agent: {
        run: vi.fn().mockImplementation(() => {
          agentCallCount++;
          if (agentCallCount === 1) {
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_GRAY_AREAS_OUTPUT }));
          }
          if (agentCallCount <= 3) {
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_DEEPDIVE_OUTPUT }));
          }
          // Scenario generation fails
          return Promise.reject(new Error('Agent timeout'));
        }),
        crossVerify: vi.fn().mockResolvedValue([]),
        listProviders: vi.fn().mockResolvedValue(['claude-code-cli']),
      } as unknown as SkillContext['agent'],
    });

    const result = await discussSkill.execute(ctx);

    // Should still succeed (partial failure is OK)
    expect(result.success).toBe(true);

    // CONTEXT.md should still be written
    expect(mockedWritePhaseArtifact).toHaveBeenCalled();

    // Scenarios should NOT have been written (they failed)
    expect(ctx.fileStore.write).not.toHaveBeenCalled();

    // Should have warnings
    expect(result.warnings).toBeDefined();
    expect(result.warnings!.length).toBeGreaterThan(0);
  });

  // -------------------------------------------------------------------------
  // Phase override via args
  // -------------------------------------------------------------------------

  it('uses --phase override when provided', async () => {
    let agentCallCount = 0;
    const ctx = createMockContext({
      args: { phase: 3 },
      agent: {
        run: vi.fn().mockImplementation(() => {
          agentCallCount++;
          if (agentCallCount === 1) {
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_GRAY_AREAS_OUTPUT }));
          }
          if (agentCallCount <= 3) {
            return Promise.resolve(createMockAgentResult({ outputText: MOCK_DEEPDIVE_OUTPUT }));
          }
          return Promise.resolve(createMockAgentResult({ outputText: MOCK_SCENARIO_OUTPUT }));
        }),
        crossVerify: vi.fn().mockResolvedValue([]),
        listProviders: vi.fn().mockResolvedValue(['claude-code-cli']),
      } as unknown as SkillContext['agent'],
    });

    mockedParseRoadmap.mockReturnValue({
      phases: [
        {
          number: 3,
          name: 'Standalone TS Skills',
          description: 'Build standalone TypeScript skills',
          completed: false,
          requirements: ['SK-01'],
          plans: [],
          planCount: 6,
          completedCount: 0,
        },
      ],
      progress: [],
    });

    mockedResolvePhaseDir.mockResolvedValue('/test/project/.planning/phases/03-standalone-ts-skills');

    await discussSkill.execute(ctx);

    // Should use phase 3 for writePhaseArtifact, not 5 from STATE.md
    const writeCall = mockedWritePhaseArtifact.mock.calls[0];
    expect(writeCall[1]).toBe(3);
  });
});
