/**
 * Ship PR body prompt builder for sunco ship.
 *
 * Produces a markdown PR body with phase summary, verification status,
 * changelog, and completed plans. Kept under 4000 chars to avoid
 * GitHub truncation (Pitfall 6).
 *
 * Requirements: SHP-01, WF-03
 * Decisions: D-04 (PR body auto-generation)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ShipPrBodyParams {
  /** Phase number being shipped */
  phaseNumber: number;
  /** Human-readable phase name */
  phaseName: string;
  /** Verification verdict (PASS/WARN/FAIL) */
  verifyVerdict: string;
  /** Total number of verification findings */
  findingsCount: number;
  /** Changelog summary markdown (from changelog-writer) */
  changelogSummary: string;
  /** One-line context summary (from CONTEXT.md objective) */
  contextSummary: string;
  /** List of plan summary one-liners */
  planSummaries: string[];
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

/**
 * Build a markdown PR body for a phase ship PR.
 *
 * Sections:
 * - Summary: phase + objective
 * - Verification Status: verdict + finding count
 * - Changes: changelog summary
 * - Plans Completed: numbered list
 *
 * @param opts - PR body parameters
 * @returns Markdown PR body string (under 4000 chars)
 */
export function buildShipPrBody(opts: ShipPrBodyParams): string {
  const {
    phaseNumber,
    phaseName,
    verifyVerdict,
    findingsCount,
    changelogSummary,
    contextSummary,
    planSummaries,
  } = opts;

  const verdictEmoji =
    verifyVerdict === 'PASS' ? 'PASS' :
    verifyVerdict === 'WARN' ? 'WARN' :
    'FAIL';

  const planList = planSummaries
    .map((s, i) => `${i + 1}. ${s}`)
    .join('\n');

  // Truncate changelog if needed to stay under budget
  const MAX_CHANGELOG_CHARS = 1500;
  let truncatedChangelog = changelogSummary;
  if (changelogSummary.length > MAX_CHANGELOG_CHARS) {
    truncatedChangelog =
      changelogSummary.slice(0, MAX_CHANGELOG_CHARS) +
      '\n\n... (see CHANGELOG.md for full list)';
  }

  return `## Phase ${phaseNumber}: ${phaseName}

${contextSummary}

### Verification Status

**Verdict:** ${verdictEmoji} | **Findings:** ${findingsCount}

> See \`VERIFICATION.md\` in this PR for the full verification report.

### Changes

${truncatedChangelog || '(no changes recorded)'}

### Plans Completed

${planList || '(no plans)'}

---

*Generated by sunco ship*`;
}
