/**
 * Ultraplan prompt builders for bridging SUNCO planning pipeline
 * with Claude Code's /ultraplan browser-based visual review.
 *
 * buildUltraplanReviewPrompt: Aggregates existing PLAN.md files + context
 * for visual review/refinement in the browser.
 *
 * buildUltraplanDraftPrompt: Creates new plans from CONTEXT/RESEARCH
 * (--draft mode only).
 *
 * parseUltraplanOutput: Converts ultraplan result back into PLAN.md files.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UltraplanReviewParams {
  /** Raw PLAN.md file contents (existing plans to review) */
  planFiles: Array<{ filename: string; content: string }>;
  /** CONTEXT.md content (optional background) */
  contextMd: string;
  /** RESEARCH.md content (optional) */
  researchMd: string;
  /** Phase goal from ROADMAP.md */
  phaseGoal: string;
  /** Requirement IDs for this phase */
  requirements: string[];
  /** Phase slug (e.g., "core-platform") */
  phaseSlug: string;
  /** Zero-padded phase number (e.g., "05") */
  paddedPhase: string;
}

export interface UltraplanDraftParams {
  contextMd: string;
  researchMd: string;
  requirementsMd: string;
  roadmapMd: string;
  phaseGoal: string;
  requirements: string[];
  phaseSlug: string;
  paddedPhase: string;
}

// ---------------------------------------------------------------------------
// Plan format spec (shared between review and draft prompts)
// ---------------------------------------------------------------------------

const PLAN_FORMAT_SPEC = `
### SUNCO PLAN.md Format Specification

Each plan MUST include:

1. **YAML frontmatter** (between --- delimiters):
   - \`phase\`: the phase slug
   - \`plan\`: sequential number (01, 02, 03...)
   - \`type\`: "execute" or "tdd"
   - \`wave\`: number (1 = no dependencies, 2 = depends on wave 1)
   - \`depends_on\`: array of plan numbers this depends on
   - \`files_modified\`: array of file paths
   - \`autonomous\`: boolean
   - \`requirements\`: array of requirement IDs
   - \`must_haves\`: object with truths, artifacts, key_links

2. **XML sections** after frontmatter:
   - \`<objective>\`: What this plan accomplishes
   - \`<context>\`: @-references to files
   - \`<tasks>\`: Contains \`<task type="auto">\` elements with:
     - \`<name>\`, \`<read_first>\`, \`<files>\`, \`<action>\`, \`<acceptance_criteria>\`, \`<verify>\`, \`<done>\`
   - \`<verification>\`: Overall verification commands
   - \`<success_criteria>\`: High-level criteria

### Wave Rules
- No dependencies = wave 1
- Depends on wave 1 plans = wave 2
- Plans in the same wave execute in parallel

### Critical Rules
- Every requirement ID must appear in at least one plan
- Each task action must be executable without ambiguity
- 2-3 tasks per plan
- Every task MUST have <read_first> and <acceptance_criteria>

### Output Format
Separate each complete PLAN.md with \`---PLAN_SEPARATOR---\`
`.trim();

// ---------------------------------------------------------------------------
// Review prompt (default mode: existing plans → browser review)
// ---------------------------------------------------------------------------

/**
 * Build a prompt for reviewing existing PLAN.md files via /ultraplan.
 * The browser reviewer sees the full plans and can comment/refine inline.
 */
export function buildUltraplanReviewPrompt(params: UltraplanReviewParams): string {
  const {
    planFiles,
    contextMd,
    researchMd,
    phaseGoal,
    requirements,
    phaseSlug,
    paddedPhase,
  } = params;

  const planSection = planFiles
    .map((pf) => `#### ${pf.filename}\n\n\`\`\`\n${pf.content}\n\`\`\``)
    .join('\n\n');

  return `# Ultraplan Review: Phase ${paddedPhase} — ${phaseSlug}

## Phase Goal
${phaseGoal}

## Requirements to Cover
${requirements.map((r) => `- ${r}`).join('\n')}

## Existing Plans to Review

The following PLAN.md files have been generated by \`sunco plan\`. Review each plan for:
- **Completeness**: Do the plans cover all requirements listed above?
- **Clarity**: Can a fresh agent execute each task without asking questions?
- **Correctness**: Are file paths, function names, and action steps accurate?
- **Wave assignment**: Are dependencies and parallel execution groups correct?
- **Risk**: Are there missing edge cases, security concerns, or brittle assumptions?

${planSection}

## Background Context

### CONTEXT.md (Phase decisions)
${contextMd || '(Not available)'}

### RESEARCH.md (Technical research)
${researchMd || '(Not available)'}

## Instructions

1. Review each plan carefully. Comment on specific sections that need improvement.
2. If changes are needed, produce the revised plans in SUNCO format.
3. If plans look good, confirm with a brief summary of why they are ready.

When producing revised plans, follow this format exactly:

${PLAN_FORMAT_SPEC}
`.trim();
}

// ---------------------------------------------------------------------------
// Draft prompt (--draft mode: new plans from context)
// ---------------------------------------------------------------------------

/**
 * Build a prompt for creating new plans via /ultraplan (--draft mode).
 * Used when no PLAN.md files exist yet.
 */
export function buildUltraplanDraftPrompt(params: UltraplanDraftParams): string {
  const {
    contextMd,
    researchMd,
    requirementsMd,
    roadmapMd,
    phaseGoal,
    requirements,
    phaseSlug,
    paddedPhase,
  } = params;

  return `# Ultraplan Draft: Phase ${paddedPhase} — ${phaseSlug}

## Phase Goal
${phaseGoal}

## Requirements to Cover
${requirements.map((r) => `- ${r}`).join('\n')}

## Input Documents

### CONTEXT.md
${contextMd}

### RESEARCH.md
${researchMd || '(No research available)'}

### REQUIREMENTS.md
${requirementsMd || '(No requirements file available)'}

### ROADMAP.md
${roadmapMd || '(No roadmap available)'}

## Instructions

Create 2-5 execution plans for this phase. Each plan should have 2-3 tasks.

${PLAN_FORMAT_SPEC}
`.trim();
}

// ---------------------------------------------------------------------------
// Output parser (import mode: ultraplan result → PLAN.md strings)
// ---------------------------------------------------------------------------

/** Separator used between plans in ultraplan output */
const PLAN_SEPARATOR = '---PLAN_SEPARATOR---';

/**
 * Parse ultraplan output into individual PLAN.md content strings.
 *
 * Only accepts structured output:
 * - Case A: Output uses ---PLAN_SEPARATOR--- markers → split and return
 * - Case B: Multiple frontmatter-delimited plans (--- ... --- blocks)
 * - Case C: Single plan with frontmatter + XML tags
 *
 * Unstructured markdown (e.g., "looks good" summaries) returns empty array
 * to prevent accidental overwrite of existing plans.
 */
export function parseUltraplanOutput(
  content: string,
  _phaseNumber: number,
  _phaseSlug: string,
): string[] {
  const trimmed = content.trim();
  if (!trimmed) return [];

  // Case A: Has PLAN_SEPARATOR markers
  if (trimmed.includes(PLAN_SEPARATOR)) {
    return trimmed
      .split(PLAN_SEPARATOR)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
  }

  // Case B: Multiple frontmatter-delimited plans
  const fmBlocks = splitByFrontmatter(trimmed);
  if (fmBlocks.length > 0) {
    return fmBlocks;
  }

  // Case C: Single plan with frontmatter + XML objective tag
  if (trimmed.includes('---\n') && trimmed.includes('<objective>')) {
    return [trimmed];
  }

  // Unstructured content — reject to prevent accidental overwrite
  return [];
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Split content that contains multiple frontmatter-delimited plans.
 * Looks for patterns like: --- ... --- ... <objective> that repeat.
 */
function splitByFrontmatter(content: string): string[] {
  // Match each plan: starts with --- (frontmatter open), has content, ends before next ---\n
  const planRegex = /(?:^|\n)(---\n[\s\S]*?\n---[\s\S]*?)(?=\n---\n|$)/g;
  const plans: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = planRegex.exec(content)) !== null) {
    const plan = match[1].trim();
    // Only include if it looks like a real plan (has frontmatter + some content)
    if (plan.startsWith('---') && plan.length > 50) {
      plans.push(plan);
    }
  }

  // Only return if we found multiple plans; single plan handled by caller
  return plans.length > 1 ? plans : [];
}

